name: "B.A.'s Gridsite"
favicon: null
layout_spectrum: 0.34432781930081546
typography_spectrum: 0.15304765454493463
title: "B.A.'s Gridsite"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.5078840849455446
  lightness: 0.0019395065028220415
  saturation: 0.07945998874492943
  rhythmicContrast: 0.5293778150808066
purpose: []
