name: "B.A.'s Gridsite"
favicon: null
layout_spectrum: 0.484
typography_spectrum: 0.38039
title: "B.A.'s Gridsite"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0e0a09'
    - '#7c7e8a'
    - '#444247'
    - '#d4c2b7'
    - '#8c513b'
  brandStrength: 0.8125
  lightness: 0.5
  saturation: 0.875
  rhythmicContrast: 0.75
purpose: []
